---
version: '3.9'
services:
  hh:
    image: rootshellcoder/hh-ru-auto-resume-raising:latest
    restart: always
    environment:
      - phone=79876543210
      - password=qwerty123
      - proxy=None
      - bot_token=1111111:a1a1a1a1a1a
      - admin_tg=01020304
      - time_zone=Europe/Moscow
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 64M
        reservations:
          cpus: '0.1'
          memory: 32M
